### ISSUE TITLE
Does ngx-quill works for Ionic 4

### ISSUE THREAD

**Issue by ArsalanSavand** [KillerCodeMonkey/ngx-quill-ionic-v3#2]
Ionic 4 beta came out a while ago, and I was wondering if I can use ngx-quill for ionic 4 beta.

If that's possible, do you think I'm going to face some issues?

**Comment by KillerCodeMonkey** [comment]
Nope ngxquill works with angular 7 so IT should work for Ionic 4 + angular
7.

But i think You should Check the hinter in the readme with user-select CSS
Attribute

Am Mo., 17. Dez. 2018, 21:32 hat Arsalan Savand <notifications@github.com>
geschrieben:

**Comment by ArsalanSavand** [comment]
Thanks for your respond.

**Comment by JahazielSam** [comment]
how can i get the < quill-editor > content to my .ts page .?? I'm using ionic 4 and i couldn't fetch any editor's content to store in my DB . Thanks

**Comment by KillerCodeMonkey** [comment]
There is an Ionic v4 Demo Linked in the Main repos readme :)

Am Mi., 20. Feb. 2019, 06:29 hat Jahaziel Samraj <notifications@github.com>
geschrieben:

**Comment by dhinukc** [comment]
@KillerCodeMonkey Thank you
