### ISSUE TITLE
couldn't get the < quill-editor > content value from html to typescript (.ts) page in Ionic 4

### ISSUE THREAD

**Issue by JahazielSam** [KillerCodeMonkey/ngx-quill-ionic-v3#3]
I'm using ionic 4 and i have just added the editor to my html page , but i couldn't get any of the < quill-editor  > content  to my .ts (typescript) page. Can anyone help please??  Thanks.

**Comment by KillerCodeMonkey** [comment]
Dude i answered in the Other issue. There is an Ionic v4 example linked in
the ngx-quill Repo.

And There IS a Link to the live Demo.

Am Mi., 20. Feb. 2019, 06:34 hat Jahaziel Samraj <notifications@github.com>
geschrieben:

**Comment by JahazielSam** [comment]
Thanks for the response. 
I already saw this demo https://github.com/KillerCodeMonkey/ngx-quill-ionic-v4 and implemented the html view of the editor it helped me greatly.
But there is no code to send up the editor's content to the .ts page to store in my DB.
it just has the < quill-editor > and < / quill-editor > tags written.

**Comment by KillerCodeMonkey** [comment]
Because this is described in the readme and the advanced examples. Use
angulars ngModel or formControl to Store the content automatically when the
User types Something in.

Or Just Listen to the onContentChanged Output and Store IT manually.

Am Mi., 20. Feb. 2019, 06:48 hat Jahaziel Samraj <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill#config
https://github.com/KillerCodeMonkey/ngx-quill#outputs

formControl:
https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/reactive-forms

ngModel:
https://github.com/KillerCodeMonkey/ngx-quill-example/tree/e7b0c27dfa7f50f0dda89712575a14005135f7d5/src/app/format-text

onContentChanged listener in the template:
https://github.com/KillerCodeMonkey/ngx-quill-example/tree/57fda57ded2b6706d0f60fa164fa8fc1478dae4b/src/app/no-toolbar

onContentChanged listener in the page:
https://github.com/KillerCodeMonkey/ngx-quill-example/tree/a498bd8f45b927ffb45378a2fd7d1f3f5a786da4/src/app/reactive-forms

**Comment by KillerCodeMonkey** [comment]
For the ionic example repos the only interesting thing is, how to integrate the quill and ngx-quill as a dependency to the build process and what or other pitfalls --> see the readmes with the css and user-select hint :).

So the main usage examples are in the advanced demo. :)

**Comment by JahazielSam** [comment]
Thanks a lot for your resources. It really helped me a lot. I am happy that i got the idea to proceed further .
